### ISSUE TITLE
Add *.class files to the apk

### ISSUE THREAD

**Issue by yrouban** [android-workloads/JACWfA#1]
This benchmark is good for both Java and Dalvik.
Create one APK for both Java and Dalvik - just add *.class files and native libs for Linux and Windows to the APK. 
Optionally make the JAR extract all needed files on its own. So, there would be no installation needed.

All these would allow Java users to run the JACWA out of the box:
  java -jar JACWA.apk

**Comment by avignate-intel** [comment]
This is resolved in 1.1 Release
